export const countries = [
  // América do Sul
  'Argentina',
  'Bolivia (Bolivia)',
  'Brazil (Brasil)',
  'Chile',
  'Colombia',
  'Ecuador',
  'Guyana',
  'Paraguay',
  'Peru (Perú)',
  'Suriname',
  'Uruguay',
  'Venezuela',

  // América do Norte
  'Canada',
  'Mexico (México)',
  'United States',

  // Europa
  'Albania (Shqipëri)',
  'Andorra',
  'Armenia (Հայաստան)',
  'Austria (Österreich)',
  'Azerbaijan (Azərbaycan)',
  'Belarus (Беларусь)',
  'Belgium (België)',
  'Bosnia and Herzegovina (Bosna i Hercegovina)',
  'Bulgaria (България)',
  'Croatia (Hrvatska)',
  'Cyprus (Κύπρος)',
  'Czech Republic (Česká republika)',
  'Denmark (Danmark)',
  'Estonia (Eesti)',
  'Finland (Suomi)',
  'France',
  'Georgia (საქართველო)',
  'Germany (Deutschland)',
  'Greece (Ελλάδα)',
  'Hungary (Magyarország)',
  'Iceland (Ísland)',
  'Ireland (Éire)',
  'Italy (Italia)',
  'Latvia (Latvija)',
  'Lithuania (Lietuva)',
  'Luxembourg (Lëtzebuerg)',
  'Malta',
  'Moldova (Republica Moldova)',
  'Monaco',
  'Montenegro (Crna Gora)',
  'Netherlands (Nederland)',
  'North Macedonia (Северна Македонија)',
  'Norway (Norge)',
  'Poland (Polska)',
  'Portugal',
  'Romania (România)',
  'Russia (Россия)',
  'San Marino',
  'Serbia (Србија)',
  'Slovakia (Slovensko)',
  'Slovenia (Slovenija)',
  'Spain (España)',
  'Sweden (Sverige)',
  'Switzerland (Schweiz)',
  'Turkey (Türkiye)',
  'Ukraine (Україна)',
  'United Kingdom',
  'Vatican City (Città del Vaticano)',

  // Austrália
  'Australia',
]
